#####################################################################################################
#
# R code for example in 
# Re: Using numerical methods to design simulations: revisiting the balancing intercept
# Paul Zivich and Rachael Ross
#
# Objective: solve for intercepts in data generating models to achieve desired marginal distribution
#
#####################################################################################################

# Libraries
#install.packages("tidyverse")
#install.packages("rootSolve")
#install.packages("Hmisc")
library("tidyverse")
library("rootSolve")
library("Hmisc")

set.seed(123)

### Setup baseline data 
n <- 1e7      # Large n to reduce simulation error
X <- rnorm(n) # Confounder X data from standard normal


### Function to be solved - this function will be called to solve for intercepts in each data generation model
tosolve <- function(ints, fxname, goalmarg){
  values <- fxname(ints)                          # simulated individual expected values at given intercept value
  
  if(is.null(dim(values))){                        # obtain mean of simulated individual expected values
    empmeans <-  mean(values)
  }else{
    empmeans <-  colMeans(values)
  }     

  diff = empmeans - goalmarg                      # difference from empirical mean to goal marginal distribution
  return(diff)                              
}


#############################
### Binomial exposure A 
# Pr(A|X)=1/(1+exp(-(alpha_0 + alpha_coefs[1]*X)))
alpha_coefs <- 0.25     # alpha model coefficients
goalmarg_a <- 0.45      # desired marginal prevalence of exposure A

# Function to generate probability of A at given intercept
gen_pr_a <- function(alpha0){
  prob_a <- plogis(alpha0[1] + alpha_coefs[1]*X)   # probability generated by model at given intercept value
  return(prob_a)
}

# Solve for alpha0
roota <- multiroot(f=tosolve, start=c(-1), fxname=gen_pr_a, goalmarg=goalmarg_a, atol=1e-12)$root # find root for exposure model

# Simulate A
A <- rbinom(n, size=1, p=gen_pr_a(roota))  # simulate A using intercept solution

#############################
### Multinomial mediator M 
# pr(M=1|A,X)/Pr(M=0|A,X) = exp(beta_10 + beta_coefs1[1]*A + beta_coefs1[2]*X)
# pr(M=2|A,X)/Pr(M=0|A,X) = exp(beta_20 + beta_coefs2[1]*A + beta_coefs2[2]*X)
beta_coefs1 <- c(1.2, -0.15)    # beta model coefficients (M=1 model)
beta_coefs2 <- c(0.65, -0.07)   # beta model coefficients (M=2 model)
goalmarg_m <- c(0.50, 0.35)     # desired marginal probability of mediator M (M=1,M=2)

# Function to generate probabilities of M at given intercepts
gen_pr_m <- function(beta0){
  odds <- matrix(nrow=n, ncol=2)                                    # create empty matrix to store odds
  odds[,1] <- exp(beta0[1] + beta_coefs1[1]*A + beta_coefs1[2]*X)   # odds(1vs0) at given intercept value
  odds[,2] <- exp(beta0[2] + beta_coefs2[1]*A + beta_coefs2[2]*X)   # odds(2vs0) at given intercept value
  denom <- as.matrix(1 + rowSums(odds))                             # sum of 3 odds to be used as denominator of pr
  prob_m <- cbind(1/denom, odds[,1]/denom)                          # probabilities for M=0 and M=2
  return(prob_m)
}

# Solve for beta intercepts
rootm <- multiroot(f=tosolve, start=c(-2,-2), fxname=gen_pr_m, goalmarg=goalmarg_m, atol=1e-12 )$root # find root for mediator model

# Get probabilities at solution & sim A
prM <- cbind(gen_pr_m(rootm), 1 - rowSums(gen_pr_m(rootm)))  # obtain probabilities for each M level using intercept solutions
M <- Hmisc::rMultinom(prM,1) - 1                             # simulate multinomial M, subtract 1 so levels are 0,1,2

#############################
### Continuous outcome Y
# E(Y) = gamma_0 + gamma_coefs[1]*A + gamma_coefs[2]*(M==1) + gamma_coefs[3]*(M==2) + gamma_coefs[4]*X

gamma_coefs <- c(-1.55, 0.25, 0.45, 0.25)   # gamma model coefficients
goalmarg_y <- 10                            # desired marginal expectation of outcome Y

# Function generate mean of Y at given intercept
gen_m_y <- function(gamma0){
  mean_y <- gamma0 + gamma_coefs[1]*A + gamma_coefs[2]*(M==1) + gamma_coefs[3]*(M==2) + gamma_coefs[4]*X   # individual Y mean at given intercept value
  return(mean_y)
}

# Find gamma0
rooty <- multiroot(f=tosolve, start=10, fxname=gen_m_y, goalmarg=goalmarg_y, atol=1e-12)$root # find root for outcome model

# Sim Y
Y <- gen_m_y(rooty) + rnorm(n, mean = 0, sd = 3) # simulate outcome Y using intercept solution

#############################
### Results
roota
mean(A)
rootm
prop.table(table(M))
rooty
mean(Y)


############################ 
## Compare result using Robertson fx
datmat <- data.frame(int=rep(1,n),X)

determine_intercept(external_data=datmat,
                               tolerance = .0001,
                               marg = goalmarg_a,
                               beta_vec = alpha_coefs)






